modLoader = "javafml"
loaderVersion = "[1,)"
license = "ARR"
issueTrackerURL = "https://github.com/terrarium-earth/Tempad/issues"

[[mods]]
modId = "tempad"
version = "${version}"
displayName = "Tempad"
displayURL = "https://modrinth.com/mod/tempad"
logoFile = "icon.png"
authors = "CodexAdrian"
credits = "MsRandom1, ThatGravyBoat, Kekie6, AlexNijjar, ShrimpPixels, Jooosh, abused_master"
description = "Create a portal to anywhere from anywhere!"

[[dependencies.tempad]]
modId = "neoforge"
type = "required"
versionRange = "[20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tempad]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tempad]]
modId = "resourcefullib"
type = "required"
versionRange = "[2.4.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tempad]]
modId = "resourcefulconfig"
type = "required"
versionRange = "[2.4.2,)"
ordering = "NONE"
side = "BOTH"
